### ISSUE TITLE
[Package Issue]: CGSecurity.TestDisk is not being properly handled

### ISSUE THREAD

**Issue by jfernandz** [microsoft/winget-pkgs#108744]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

Package is not being properly installed/uninstalled.

### Steps to reproduce

Run `winget install CGSecurity.TestDisk`

Check availability of newly created aliases.

They aren't available even after restarting pwsh.

### Actual behavior

`winget install CGSecurity.TestDisk` will show you all new aliases created, but they don't work at all.

After `winget uninstall CGSecurity.TestDisk` you'll show some files will remain at `%LOCALAPPDATA%/Microsoft/WinGet/Packages/`

### Expected behavior

`winget install` and `winget uninstall` should perform proper install/uninstall actions.

### Environment

```raw
 winget --info
Administrador de paquetes de Windows v1.4.10173
Copyright (c) Microsoft Corporation. Todos los derechos reservados.

Windows: Windows.Desktop v10.0.22621.1778
Arquitectura del sistema: X64
Paquete: Microsoft.DesktopAppInstaller v1.19.10173.0

Registros: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Configuración de usuario: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json

Vínculos
-----------------------------------------------------------------------------------
Declaración de privacidad   https://aka.ms/winget-privacy
Contrato de licencia        https://aka.ms/winget-license
Avisos de terceros          https://aka.ms/winget-3rdPartyNotice
Página principal            https://aka.ms/winget
Términos de Microsoft Store https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

**Comment by Trenly** [comment]
This should be resolved on the latest 1.5-preview version of winget. Can you see if the newer version of the client fixes your issue? 

You may have to uninstall, upgrade to the 1.5-preview, and then reinstall TestDisk

**Comment by jfernandz** [comment]
@Trenly thank you for your answer! 😄

I forgot to uninstall TestDisk before upgrading to 1-5-preview and right now it's not being properly uninstalled, when I use `uninstall` command it get stuck

```
> winget uninstall --verbose CGSecurity.TestDisk
Encontrado TestDisk [CGSecurity.TestDisk]
Iniciando la desinstalación de paquete...
```

So not sure what's the most proper way to uninstall it ... 😞 

Also ... Not sure why `winget` doesn't use the system locale (which is set as en-US)

```
> Get-WinSystemLocale
LCID             Name             DisplayName
----             ----             -----------
1033             en-US            English (United States) 
```

**Comment by jfernandz** [comment]
`GeekUninstaller.GeekUninstaller` and its `Force Removal` option did a good work, and after installing TestDisk again with `1.5-preview` of winget it works as expected 😄

But still not sure about the locale problem, should I open a specific bug for it? 🤔

**Comment by PurplProto** [comment]
I'm using Winget `v1.10.340` and it does seem to install. Looking in the manifest file I could see one of the commands to use it `photorec_win`, but it complains it's missing required libraries. So I guess this means it's still not being properly installed ☹️
