### ISSUE TITLE
LLVM.LLVM package does not register PATH

### ISSUE THREAD

**Issue by saschanaz** [microsoft/winget-pkgs#11767]
# Brief description of your issue

... thus the clang command is not exposed to system.

# Steps to reproduce

`winget install LLVM.LLVM`

# Expected behavior

It should register PATH.

# Actual behavior

It does not.

# Environment

```none
Windows Package Manager v0.3.11102 Preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19043.962
Package: Microsoft.DesktopAppInstaller v1.11.11102.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
--------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
```

**Comment by denelon** [comment]
I'm not familiar with LLVM. It looks like a collection of command-line tools. I'm not sure if the installer registers the path or not. It may require a terminal restart to get the path if the installer does set the path.

**Comment by saschanaz** [comment]
@denelon It provides an option to register the path, and the manifest seems not to use that option.

**Comment by denelon** [comment]
https://github.com/microsoft/winget-cli/issues/222 is a feature request to refresh the path after install. Would that address this situation?

**Comment by saschanaz** [comment]
I don't think so, the default option from the installer is not to register path, but when someone install a package via CLI the default expectation is to get a path (IMO at least), so I think the manifest should be somehow updated.

**Comment by denelon** [comment]
Is setting the path just passing a flag to the installer? If that is the case, the switches could be modified to pass the flag. If it requires passing the desired path to the installer, I'm not sure that would be an option at this point.

**Comment by saschanaz** [comment]
>Is setting the path just passing a flag to the installer?

It gives three options in GUI:

* No PATH
* System PATH
* User PATH

I'm not sure what flag should be given (or whether it even receives a flag) when running it via CLI since I don't see a documentation for that.

**Comment by denelon** [comment]
The manifest has:

```YAML
InstallerSwitches:
  InstallLocation: /D=<INSTALLPATH>
```

https://github.com/microsoft/winget-cli/tree/master/schemas/JSON/manifests/v1.0.0
lists the JSON schemas declaring what switches can be used.

It looks like this might be suitable for "Custom". You may need to test with a local manifest to see which one handles the scenario correctly. You can copy the manifest files to your local system and then `winget install -m <path to manifest>` to test locally. If you have the experimental "uninstall" feature enabled, you can quickly uninstall, modify the manifest, and try again. Remember you likely have to restart your terminal/shell to get the path variable to become active.

**Comment by saschanaz** [comment]
Only if I know what "custom" flag it receives 😄

**Comment by lychichem** [comment]
Maybe you should first try to know which tool is used to pack the installer. For example, when installed via winget, VSCode can register path/association/context menu by using switch `--override '/silent /TASKS="addcontextmenufiles,addcontextmenufolders,associatewithfiles,addtopath"'`, and these switches are defined in the script used to package VSCode installer.

**Comment by saschanaz** [comment]
Seems it uses NSIS [per the build script](https://github.com/llvm/llvm-project/blob/638d84b60b7e7b7fa9099939ab4de2ec1e0c52c3/llvm/CMakeLists.txt#L233).

**Comment by lychichem** [comment]
> Seems it uses NSIS [per the build script](https://github.com/llvm/llvm-project/blob/638d84b60b7e7b7fa9099939ab4de2ec1e0c52c3/llvm/CMakeLists.txt#L237).

This is not enough... See https://github.com/microsoft/vscode/blob/94c9ea46838a9a619aeafb7e8afd1170c967bb55/build/win32/code.iss#L79 , you'll need to know the possible tasks/sections in install script.

**Comment by saschanaz** [comment]
CPACK_NSIS_MODIFY_PATH is the CPack API to add a relevant option page to the NSIS installer.

[This is the underlying source](https://github.com/Kitware/CMake/blob/c58ec3209bbd117f8b5078f0e188d15d98cdd3fb/Modules/Internal/CPack/NSIS.template.in#L703-L737) to interact with NSIS, but I'm not sure what it really does.

**Comment by lychichem** [comment]
> [CPACK_NSIS_MODIFY_PATH](https://cmake.org/cmake/help/latest/cpack_gen/nsis.html#variable:CPACK_NSIS_MODIFY_PATH) is the CPack API to add a relevant option page to the NSIS installer.
> 
> [This is the underlying source](https://github.com/Kitware/CMake/blob/c58ec3209bbd117f8b5078f0e188d15d98cdd3fb/Modules/Internal/CPack/NSIS.template.in#L703-L737) to interact with NSIS, but I'm not sure what it really does.

Maybe you can try the command listed [here](https://nsis.sourceforge.io/Reference/Section)? By passing `--override '<some commands>` to winget

**Comment by denelon** [comment]
Has anybody been able to determine which flags need to be passed to the installer to register the path for LLVM?

**Comment by saschanaz** [comment]
Chocolatey [manually registers the path](https://community.chocolatey.org/packages/llvm#files) (see `Install-ChocolateyPath` at the last line), maybe the same should be done here?

**Comment by saschanaz** [comment]
I think I did respond 🤨

**Comment by saschanaz** [comment]
Can someone remove that label please?

**Comment by Trenly** [comment]
I believe this was resolved? It looks like the switch is present in - 
- https://github.com/microsoft/winget-pkgs/pull/42144/

**Comment by denelon** [comment]
Was this resolved by LLVM with their latest update?

**Comment by Trenly** [comment]
> Was this resolved by LLVM with their latest update?

No; I was just looking at the wrong file. Sorry for the ghost ping

**Comment by nlhnt** [comment]
Still not resolved, ehh.  
I had problems with scoop, because it registers some powershell script instead of the executable, so my IDE doesn't recognise the clang executable.  
I thought, let's give winget a try, and it doesn't even register it, I don't even know where it was downloaded (wasn't reported by the tool during the installation).  
I end up having to manually setup the path anyway, but first I need to manually figure out the installation.  
Sorry that I sound dissapointed, I just expected a little bit more.  
Keep up the good work I guess 👍🏻

**Comment by denelon** [comment]
@nlhnt,
We're working on:

* microsoft/winget/issues/140

Some of the work in that feature is related to registering applications. Maybe there will be a way to leverage the path logic after that is complete. I'll bring it up to the team. Is LLVM open source? Maybe they would have insight into command line switches to register a path via silent install.

**Comment by superusercode** [comment]
>  Is LLVM open source? Maybe they would have insight into command line switches to register a path via silent install.

LLVM is open source. I started looking into the project since they use nullsoft for their installer but it's hard to tell how they have it configured since they use cmake on top (with the solution file equivalent here https://github.com/llvm/llvm-project/blob/main/llvm/CMakeLists.txt). I've put in an issue (https://github.com/llvm/llvm-project/issues/54724) and will be able to determine from there if they have nullsoft configured to allow setting the path.

**Comment by superusercode** [comment]
LLVM uses cmake to generate their nullsoft installer, so they haven't enabled any commandline flags aside from the default nullsoft ones. In order to enable a silent install of LLVM that sets the path someone would have to contribute that option to the previously mentioned CMakeLists file. 

This was explained in the most recent comment in response to the LLVM issue, and I will be adjusting the question into a feature request since I'm not sure how to implement this myself.

**Comment by denelon** [comment]
Related to:

* https://github.com/llvm/llvm-project/issues/54724

**Comment by jingkecn** [comment]
Try `winget install -I LLVM.LLVM` then you will have the option to register LLVM to the path for current user/all users.

**Comment by AMDphreak** [comment]
> Try `winget install -i LLVM.LLVM` then you will have the option to register LLVM to the `PATH` for current user/all users.

Any chance this can be truly fixed and not resorting to a dumb work-around that requires user attention?

**Comment by matormentor** [comment]
Also stumbled upon this recently, any chance it can be fixed?

**Comment by ratijas** [comment]
> Try `winget install -i LLVM.LLVM` then you will have the option to register LLVM to the PATH for current user/all users.

Alternatively, you could adjust the PATH from command line as well:

```powershell
winget install -e --id LLVM.LLVM
# Only for current user:
[Environment]::SetEnvironmentVariable("Path", "$([Environment]::GetEnvironmentVariable("Path", "User"));C:\Program Files\LLVM\bin", "User")
# or system-wide:
[Environment]::SetEnvironmentVariable("Path", "$([Environment]::GetEnvironmentVariable("Path", "Machine"));C:\Program Files\LLVM\bin", "Machine")
```

Funny enough, I have already so many tools installed from winget and other places, that LLVM interactive installer refused to modify it, saying "PATH too long". For a second I though it means Windows file system path limit (which should be disabled anyway), but nope -- it meant the actual PATH environment variable. So as you can see, `winget install -i` can be pretty useless.
