### ISSUE TITLE
Updated IntelliJ keeps showing upgrade for latest version

### ISSUE THREAD

**Issue by pc-v2** [microsoft/winget-pkgs#15345]
Create issues related to the winget.exe client [here](https://github.com/microsoft/winget-cli/issues/new?template=Bug_Report.md)

# Brief description of your issue

I have upgraded my Intellij to 2021.1.1 and winget still showing there's an upgrade for intellij (I noticed winget using different methods to showcase the version number)
# Steps to reproduce

1. install Intellij like usually
# Expected behavior

Version number has same method

# Actual behavior

version number is different
IntelliJ IDEA Community Edition           JetBrains.IntelliJIDEA.Community           211.7142.45          2021.1.1  winget
![image](https://user-images.githubusercontent.com/58063311/120259899-039b8d00-c2bf-11eb-8a52-3cae3861e6fc.png)

# Environment
```none
[winget --info]
Windows: Windows.Desktop v10.0.19043.1023
Package: Microsoft.DesktopAppInstaller v1.11.11451.0
Any other software?
```

**Comment by GeorgeCY2** [comment]
try submitting the newer version of Jetbrains IntelliJ, That's one way you can solve it.

as far as I know this is so far a bug with checking versions and everything, for example I could have speccy 1.32.77, and the author of that program made it so that it lists it on windows apps as 1.32 and then winget will think that it needs an upgrade to 1.32.77 when I already have that version, so yeah it is currently buggy and one way you can solve it submitting the newer version of the program.

**Comment by jedieaston** [comment]
It's because IntelliJ uses different version numbers for the actual install vs marketing. We've been using the marketing version number, there's not a fast way to migrate it since they don't really publish it anywhere but in the installer. This is another scenario where we need to be able to list multiple version numbers for a single manifest.

**Comment by abdonmorales** [comment]
This issue was solved with PR:

#15820
#15800
#15805

This issue can now be closed

**Comment by pc-v2** [comment]
![image](https://user-images.githubusercontent.com/58063311/120879370-06fb8500-c5ed-11eb-8ff2-79b71b2d5630.png)
it still showing 2020.3 on my machine

**Comment by pc-v2** [comment]
isn't it should be showing 211.xxx?

**Comment by abdonmorales** [comment]
@pc-v2 Try and upgrade IntelliJ

**Comment by abdonmorales** [comment]
It should pull the new fix from the repository

**Comment by pc-v2** [comment]
> It should pull the new fix from the repository

okay

**Comment by pc-v2** [comment]
> It should pull the new fix from the repository

![image](https://user-images.githubusercontent.com/58063311/120879578-a705de00-c5ee-11eb-9d44-b12717d07852.png)
nope, still 2020.3

**Comment by abdonmorales** [comment]
Okay, let me double-check the manifest of 2020.3, if it's a manifest issue it should be fixed, but I really think it might be CLI issue

**Comment by abdonmorales** [comment]
Okay this PR #16310 should fix the problem for you @pc-v2

**Comment by abdonmorales** [comment]
It seems there was no build number for this version on the website of JetBrains

**Comment by pc-v2** [comment]
the new ones are 211.7442.40, ![image](https://user-images.githubusercontent.com/58063311/120879833-6c9d4080-c5f0-11eb-84b1-097d995c00ff.png)

**Comment by pc-v2** [comment]
ultimate and community has same version number

**Comment by abdonmorales** [comment]
Yes, the new ones are patched, but for that version (2020.3), there's no build number at their website

**Comment by abdonmorales** [comment]
And this would break any IntelliJ Community installation due to an incomplete manifest

**Comment by abdonmorales** [comment]
Also, @pc-v2 after the PR goes through upgrade IntelliJ afterward!

**Comment by lackovic** [comment]
This is happening for **Ultimate** as well.

When running `winget upgrade -h --all` winget reports there is a new version for `JetBrains.IntelliJIDEA.Ultimate` (2022.3 -> 2022.3.1) but does not install it.

```powershell
> winget upgrade -h --all --verbose-logs
Name                 Id                              Version Available Source
-----------------------------------------------------------------------------
IntelliJ IDEA 2022.3 JetBrains.IntelliJIDEA.Ultimate 2022.3  2022.3.1  winget
1 upgrades available.
``` 

```powershell
> winget --info
Windows Package Manager v1.4.10173
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.1105
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.19.10173.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

User Settings: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

```powershell
> winget list IDEA
Name                   Id                              Version  Available Source
--------------------------------------------------------------------------------
IntelliJ IDEA 2022.3.1 JetBrains.IntelliJIDEA.Ultimate 2022.3.1           winget
IntelliJ IDEA 2022.3   JetBrains.IntelliJIDEA.Ultimate 2022.3   2022.3.1  winget
``` 

In Windows > Apps > Intalled apps I had two IntelliJ IDEA versions installed:

![2023-01-25_092032](https://user-images.githubusercontent.com/1663053/214503265-00d15943-ddf5-4d42-be41-b29000539553.png)

Removing the older version fixed the issue.

```powershell
> winget list IDEA
Name                   Id                              Version  Source
-----------------------------------------------------------------------
IntelliJ IDEA 2022.3.1 JetBrains.IntelliJIDEA.Ultimate 2022.3.1 winget

> winget upgrade -h --all --verbose-logs
No installed package found matching input criteria.
```
