### ISSUE TITLE
Prompt for UAC elevation when installing VirtualBox

### ISSUE THREAD

**Issue by mariobrostech** [microsoft/winget-pkgs#25986]
# Brief description of your issue
The installation of VirtualBox via `winget` fails with exit code 1 unless an admin PowerShell prompt is already open.

# Steps to reproduce
1. Open PowerShell as a non-elevated user.
2. Attempt to install VirtualBox via `winget`.
3. Observe the installation failing with exit code 1.

# Expected behavior
When trying to install VirtualBox via `winget` as a standard user, the user should be presented with a User Account Control elevation prompt to allow the installation to proceed.

# Actual behavior
When trying to install VirtualBox via `winget` as a standard user, the user is not presented with a User Account Control elevation prompt, and the installer silently fails.
# Environment

```none
[winget --info]
Windows: Windows.Desktop v10.0.19042.1165
Package: Microsoft.DesktopAppInstaller v1.12.11692.0

**Comment by lychichem** [comment]
Strongly agree to apply it to other packages, for example, tencentmeeting, as it cannot install anything and exits with no exit code if you don't run winget as administrator. `--scope machine` will not help.

**Comment by OfficialEsco** [comment]
Hmm, try it out now? VirtualBox prompts for UAC now
tencentmeeting is fixed in the manifest but requires winget-cli to catch up

**Comment by i2** [comment]
I am still getting this exit code 1 when installing VirtualBox (v6.1.38). Any updates?

**Comment by OfficialEsco** [comment]
That's the installers job.
And we already use elevation and down elevation (If you have WinGet-CLI Version 1.3).
Some packages cannot be installed when run as Administrators from cmd and others can't be installed when not run as Administrator from cmd, there is nothing else WinGet can do when this is a developer issue.

**Comment by Trenly** [comment]
Thank you for taking the time to report this issue. In the amount of time the issue has been open, there have been several updates to the WinGet CLI which may have helped mitigate some of these concerns. I encourage you to try out the [latest version](https://github.com/microsoft/winget-cli/releases/latest) of the CLI and see if your issue still persists. If it does, please open a new issue and include any relevant log files

###### Close with reason: Stale;
