### ISSUE TITLE
Bug Report: trying to install Wireshark 0x80190194 : Not found (404)

### ISSUE THREAD

**Issue by vazome** [microsoft/winget-pkgs#442]
I tried to install Wireshark and it found the package but eventually there is an error.
```
Name                           Value
----                           -----
PSVersion                      5.1.19041.1
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```
![image](https://user-images.githubusercontent.com/46573198/82440111-7c5cec00-9aa4-11ea-81ab-efc8ccf67ac8.png)

**Comment by LukasNespor** [comment]
The installation package was removed from source server. Fixed with new Url in #446

**Comment by vazome** [comment]
> The installation package was removed from source server. Fixed with new Url in #446

It still occurs. Does it take time to update or should apply immediately?

**Comment by LukasNespor** [comment]
> > The installation package was removed from source server. Fixed with new Url in #446
> 
> It's still occurring. Does it take time to update or should apply immediately?

Yes. Owner of this repository has to approve the fix and then (after some time) it will be published to winget repository. Sorry, you have to wait.

**Comment by maxmichels** [comment]
It is not merged yet, so you are still getting the wring server url. You have to wait until #446 is merged into the repository first. You can check the status of the PR when you click here: #446

**Comment by Datakriger101** [comment]
https://winget.run/pkg/WiresharkFoundation/Wireshark

Wirehark has that download link as well, when it comes to the winget download.
