### ISSUE TITLE
[Scope] Gridcoin.Client - No applicable update found

### ISSUE THREAD

**Issue by OfficialEsco** [microsoft/winget-pkgs#47655]
So a little bird told me the 1.3 client supports the `AppsAndFeaturesEntries` field, so i went looking for issues and stumbled over this awkward issue

[Current Manifest](https://github.com/microsoft/winget-pkgs/blob/f5a653fd452ab3181817e7555fff7eed23b79e6b/manifests/g/Gridcoin/Client/5.3.2/Gridcoin.Client.installer.yaml)

<details>
<summary>Click for Log</summary>
<br>

```
2022-02-22 17:14:08.047 [CORE] WinGet, version [1.3.431-preview], activity [{80246919-FBEE-4698-AB43-D5B0DBA4EC62}]
2022-02-22 17:14:08.047 [CORE] OS: Windows.Desktop v10.0.22000.493
2022-02-22 17:14:08.047 [CORE] Command line Args: "C:\Users\User\AppData\Local\Microsoft\WindowsApps\winget.exe" upgrade -m .\g\Gridcoin\Client\5.3.2\
2022-02-22 17:14:08.048 [CORE] Package: Microsoft.DesktopAppInstaller v1.18.431.0
2022-02-22 17:14:08.048 [CORE] IsCOMCall:0; Caller: winget-cli
2022-02-22 17:14:08.050 [CLI ] WinGet invoked with arguments: 'upgrade' '-m' '.\g\Gridcoin\Client\5.3.2\'
2022-02-22 17:14:08.050 [CLI ] Found subcommand: upgrade
2022-02-22 17:14:08.050 [CLI ] Leaf command to execute: root:upgrade
2022-02-22 17:14:08.051 [CLI ] Executing command: upgrade
2022-02-22 17:14:08.052 [REPO] GetCurrentSourceRefs: Source named 'microsoft.builtin.desktop.frameworks' from origin Default is hidden and is dropped.
2022-02-22 17:14:08.052 [REPO] Default source requested, multiple sources available, adding all to source references.
2022-02-22 17:14:08.052 [REPO] Adding to source references msstore
2022-02-22 17:14:08.052 [REPO] Adding to source references winget
2022-02-22 17:14:08.052 [REPO] Multiple sources available, creating aggregated source.
2022-02-22 17:14:08.052 [REPO] Adding to aggregated source: msstore
2022-02-22 17:14:08.052 [REPO] Sending http GET request to: https://storeedgefd.dsx.mp.microsoft.com/v9.0/information
2022-02-22 17:14:08.204 [REPO] Response status: 200
2022-02-22 17:14:08.205 [REPO] Sending http GET request to: https://storeedgefd.dsx.mp.microsoft.com/v9.0/information
2022-02-22 17:14:08.262 [REPO] Response status: 200
2022-02-22 17:14:08.262 [REPO] Adding to aggregated source: winget
2022-02-22 17:14:08.269 [CORE] Examining extension: PFN = Microsoft.Winget.Source_8wekyb3d8bbwe, ID = IndexDB
2022-02-22 17:14:08.269 [CORE] Found matching extension.
2022-02-22 17:14:08.283 [REPO] Opening SQLite Index for ImmutableRead at 'C:\Program Files\WindowsApps\Microsoft.Winget.Source_2022.222.1542.299_neutral__8wekyb3d8bbwe\Public\index.db'
2022-02-22 17:14:08.283 [SQL ] Opening SQLite connection: 'file:/C:/Program Files/WindowsApps/Microsoft.Winget.Source_2022.222.1542.299_neutral__8wekyb3d8bbwe/Public/index.db?immutable=1' [1, 40]
2022-02-22 17:14:08.283 [REPO] Opened SQLite Index with version [1.3], last write [2022-02-22 15:42:13.000]
2022-02-22 17:14:08.435 [REPO] Creating PredefinedInstalledSource with filter [None]
2022-02-22 17:14:08.435 [REPO] Creating new SQLite Index [4294967295.4294967295] at ':memory:'
2022-02-22 17:14:08.435 [SQL ] Opening SQLite connection: ':memory:' [6, 0]
2022-02-22 17:14:08.477 [REPO] Examining ARP entries for Machine | X64
2022-02-22 17:14:08.483 [REPO] Examining ARP entries for Machine | X86
2022-02-22 17:14:08.486 [REPO] Examining ARP entries for User | X64
2022-02-22 17:14:08.564 [CLI ] Manifest fields: Name [Gridcoin], Version [5.3.2]
2022-02-22 17:14:08.570 [REPO] Opening SQLite Index for ReadWrite at 'C:\Users\User\AppData\Local\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\StoreEdgeFD\installed.db'
2022-02-22 17:14:08.570 [SQL ] Opening SQLite connection: 'C:\Users\User\AppData\Local\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\StoreEdgeFD\installed.db' [2, 0]
2022-02-22 17:14:08.571 [REPO] Opened SQLite Index with version [1.3], last write [2022-01-12 17:04:12.000]
2022-02-22 17:14:08.613 [REPO] Opening SQLite Index for ReadWrite at 'C:\Users\User\AppData\Local\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\Microsoft.Winget.Source_8wekyb3d8bbwe\installed.db'
2022-02-22 17:14:08.613 [SQL ] Opening SQLite connection: 'C:\Users\User\AppData\Local\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\Microsoft.Winget.Source_8wekyb3d8bbwe\installed.db' [2, 0]
2022-02-22 17:14:08.614 [REPO] Opened SQLite Index with version [1.3], last write [2022-02-22 17:11:23.000]
2022-02-22 17:14:08.667 [CLI ] Found one app. App id: Gridcoin.Client App name: Gridcoin
2022-02-22 17:14:08.668 [CLI ] Starting installer selection.
2022-02-22 17:14:08.668 [CLI ] Installer [X64,nullsoft,Machine,] not applicable: Installer scope does not match currently installed scope: Machine != User
2022-02-22 17:14:08.668 [CLI ] Installer [X86,nullsoft,Machine,] not applicable: Installer scope does not match currently installed scope: Machine != User
2022-02-22 17:14:08.674 [CLI ] Terminating context: 0x8a150010 at D:\a\_work\1\s\external\pkg\src\AppInstallerCLICore\Workflows\InstallFlow.cpp:74
```

</details>

I've tested locally and it does indeed upgrade if you replace Machine with User or just remove the scope.
HOWEVER, it requires Administrator to install and it installs to `C:\Program Files\GridcoinResearch`.

<details>
<summary>Click for Pictures</summary>
<br>

![VirtualBoxVM_3mvSXKfl2v](https://user-images.githubusercontent.com/15158490/155177582-b0dd1337-8ef5-4652-a7d5-6f63d58799b1.png)
![VirtualBoxVM_RBhiX3EtMk](https://user-images.githubusercontent.com/15158490/155177607-afe3c29a-2847-432a-bc3f-a6fda3262a9a.png)
![VirtualBoxVM_BvgSY8NgbY](https://user-images.githubusercontent.com/15158490/155177618-70bd57f3-bfb7-4c23-8003-72650f89842b.png)
![VirtualBoxVM_EPL9AXY7n4](https://user-images.githubusercontent.com/15158490/155177694-27d5ac31-19ed-438e-9119-ae6ef9385fc4.png)

</details>

So... Are we using the Scope wrong or is the Package writing to the wrong Registry path?

-----

>I have the same issue "No applicable update found" on the following packages:
>
>```winget -v```
>v1.0.11451
>
>```winget upgrade```
>
>|Name | ID | Version | Verfügbar |Quelle
>|-------|----|----------|------------|-------------------------------------------------------
>|Gridcoin |  Gridcoin.Client|5.2.2|5.3.1|winget
>
>after ```winget upgrade --all``` the same packages and versions are available. 
>
>If I use ```winget upgrade Gridcoin.Client``` I get "No applicable update found"
>
>_Originally posted by **pocki** in https://github.com/microsoft/winget-cli/issues/752#issuecomment-849890247_

**Comment by denelon** [comment]
I think we're going to have to look into this one to determine if there is something we can do, or if it's based on what the installer is doing.

**Comment by sitiom** [comment]
- Should be fixed in https://github.com/gridcoin-community/Gridcoin-Research/pull/2643

**Comment by sitiom** [comment]
> * https://github.com/gridcoin-community/Gridcoin-Research/pull/2643

PR is merged and should now be fixed in the next update. Can this issue be closed now?

**Comment by OfficialEsco** [comment]
The issue is still active unless Version with the fix is merged into the repository, the issue can be closed with
* Resolves #47655 :)

**Comment by mdanish-kh** [comment]
As described in https://github.com/microsoft/winget-pkgs/pull/100716#issuecomment-1485367224, the issue is not completely resolved even after the fix from the upstream repo. 5.4.2 would need to be "installed" first by users and subsequent upgrades will be served by WinGet.

@OfficialEsco would you feel comfortable closing the issue now or should this remain open until WinGet finds a way to reason better about scope differences?
