### ISSUE TITLE
[Package Issue]: Compuphase.Termite

### ISSUE THREAD

**Issue by ChristianBeier** [microsoft/winget-pkgs#54454]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

Termite is part of every upgrade, regardless if it was just installed or updated.

### Steps to reproduce

winget install Compuphase.Termite
Winget upgrade -all

### Actual behavior

Termite is part of every upgrade
Energy and bandwidth is wasted

### Expected behavior

Only new versions are reported and installed

### Environment

```shell
Windows Package Manager (Preview) v1.2.3411-preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22000.556
Package: Microsoft.DesktopAppInstaller v1.17.3411.0

winget show compuphase.termite
Found Termite [Compuphase.Termite]
Version: 3.4
Publisher: CompuPhase
Description: Termite is an easy to use and easy to configure RS232 terminal. It uses an interface similar to that of "messenger" or "chat" programs, with a large window that contains all received data and an edit line for typing in strings to transmit.
Homepage: https://www.compuphase.com/software_termite.htm
License: Copyright (c) CompuPhase
Installer:
  Type: exe
  Download Url: https://www.compuphase.com/software/termite-3.4.exe
  SHA256: ca440b6c7f6eaa812ba5f8bf42aed86e02022ca50a1c72585168c9b671d0fe19
```

**Comment by ItzLevvie** [comment]
This happens because the application developer doesn't display a version in Control Panel.

It's solved in WinGet version 1.3.431-preview:
![image](https://user-images.githubusercontent.com/11600822/158364592-667c7f72-7098-4b1f-93df-2383d1808370.png)

**Comment by ChristianBeier** [comment]
> It's solved in WinGet version 1.3.431-preview where versions that don't display a version won't be automatically upgraded when doing `winget upgrade --all` or something along those lines: ![image](https://user-images.githubusercontent.com/11600822/158364592-667c7f72-7098-4b1f-93df-2383d1808370.png)

I believe we agree that it is not solved; the package is only suppressed. Is the package maintainer (Termite?) working on a solution?

Wouldn't it make sense to enforce every package to provide a version number? Otherwise, a package manager makes no sense and versioning information can also be used to identify potential security risks.

**Comment by Trenly** [comment]
> This happens because the application developer doesn't display a version in Control Panel so WinGet cannot figure out the version that the user is on hence the reason why it's listed as "Unknown".

@msftbot Installer-Issue
